name: Code format

on:
  pull_request:
  workflow_dispatch:

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Checking Deno
        run: |
          deno install --allow-scripts
          deno lint
          deno fmt --check
          deno check .
          deno test
