name: Format & Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  apply:
    if: github.event.pull_request.draft == false
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: Set Git origin
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - name: Check Deno
        run: |
          deno install --allow-scripts
          deno lint --fix
          deno fmt
      - name: Push formatting changes (if any)
        run: |
          git diff --quiet || (
            git commit -a -m "style: code formatting" &&
            git push)
