name: Publish

on:
  workflow_dispatch:
    inputs:
      pre:
        description: "Optional version suffix (e.g. pre.1)"
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Update version with suffix
        if: github.event.inputs.pre != ''
        run: |
          VERSION_SUFFIX="${{ github.event.inputs.pre }}"
          # Ensure suffix starts with a dash if it doesn't already
          [[ "$VERSION_SUFFIX" != -* ]] && VERSION_SUFFIX="-$VERSION_SUFFIX"
          sed -i "s/\"version\": \"\(.*\)\"/\"version\": \"\1$VERSION_SUFFIX\"/" deno.jsonc
      - run: deno task publish
